-- Add missing discount columns to POSSale table
ALTER TABLE "POSSale"
  ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "discountType" TEXT,
  ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "discountReason" TEXT;

-- Add missing discount columns to POSSaleItem table
ALTER TABLE "POSSaleItem"
  ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "discountType" TEXT,
  ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "originalPrice" DOUBLE PRECISION;

-- Add missing columns to CompanySettings table
ALTER TABLE "CompanySettings"
  ADD COLUMN IF NOT EXISTS "vatEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "vatRegistrationNumber" TEXT,
  ADD COLUMN IF NOT EXISTS "taxInclusive" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "requireDiscountApproval" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "maxDiscountPercentage" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "discountApprovalThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- Restore default constraint for tax column
ALTER TABLE "POSSale" ALTER COLUMN "tax" SET DEFAULT 0;
